import React from 'react';
import { X, Package, Clock, CheckCircle, Truck, Phone, MessageCircle, Receipt } from 'lucide-react';
import type { Order } from '../types';
import { safeFormatNumber } from '../utils/pricing';
interface OrdersModalProps { isOpen:boolean; orders:Order[]; currency:'YER'|'SAR'; onClose:()=>void; onOpenSupport:()=>void; onOpenOrderChat?:(order:Order)=>void; }
export const OrdersModal:React.FC<OrdersModalProps>=({isOpen,orders,currency,onClose,onOpenSupport,onOpenOrderChat})=>{
 if(!isOpen)return null;
 const getStatusBadge=(status:Order['status'])=>{
  switch(status){
   case 'awaiting_payment': return <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-50 text-amber-700 border border-amber-200"><Receipt className="w-3 h-3"/>بانتظار التحويل</span>;
   case 'payment_submitted': return <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-violet-50 text-violet-700 border border-violet-200"><Receipt className="w-3 h-3"/>إشعار الدفع للمراجعة</span>;
   case 'preparing': return <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-50 text-amber-700 border border-amber-200"><Clock className="w-3 h-3"/>جاري التجهيز</span>;
   case 'in_shipping': return <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200"><Truck className="w-3 h-3"/>جاري الشحن</span>;
   case 'delivered': return <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200"><CheckCircle className="w-3 h-3"/>تم التوصيل</span>;
   default: return <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-slate-100 text-slate-700">ملغي</span>;
  }
 };
 return <div className="fixed inset-0 z-50 flex justify-end bg-black/60"><div className="bg-white w-full max-w-md h-full shadow-2xl flex flex-col" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between px-4 py-3 border-b"><div className="flex items-center gap-2"><Package className="w-5 h-5 text-purple-700"/><h2 className="font-extrabold text-sm">سجل الطلبات</h2></div><button onClick={onClose}><X className="w-5 h-5"/></button></div><div className="flex-1 overflow-y-auto p-4 space-y-3">{orders.length===0?<div className="flex flex-col items-center justify-center h-64 text-center"><Package className="w-10 h-10 text-purple-300 mb-3"/><h3 className="font-bold">لا توجد طلبات</h3></div>:orders.map(ord=><div key={ord.id} className="bg-slate-50 rounded-2xl p-4 border border-slate-200 space-y-3"><div className="flex items-center justify-between"><span className="font-mono font-bold text-xs text-purple-700">{ord.orderNumber}</span>{getStatusBadge(ord.status)}</div><div className="space-y-2 border-y py-2">{ord.items.map((item,idx)=><div key={idx} className="flex items-center gap-2 text-xs"><img src={item.image} alt={item.productName} className="w-10 h-10 object-cover rounded-lg"/><div className="flex-1 min-w-0"><span className="font-bold block truncate">{item.productName}</span><span className="text-[10px] text-slate-500">الكمية: {item.quantity} · {safeFormatNumber(item.price)} {ord.currency}</span>{item.color&&<span className="text-[10px] text-slate-500 block">اللون: {item.color}</span>}{item.size&&<span className="text-[10px] text-slate-500 block">المقاس: {item.size}</span>}</div></div>)}</div><div className="flex items-center justify-between text-xs"><span className="text-slate-500">{ord.governorate}</span><span className="font-black text-purple-700">{safeFormatNumber(ord.total)} {ord.currency||currency}</span></div><div className="flex gap-2"><button onClick={()=>onOpenOrderChat?.(ord)} className="flex-1 py-2 rounded-xl bg-purple-600 text-white text-[11px] font-bold flex items-center justify-center gap-1"><MessageCircle className="w-3.5 h-3.5"/>محادثة الطلب</button>{ord.paymentProofUrl&&<a href={ord.paymentProofUrl} target="_blank" rel="noreferrer" className="py-2 px-3 rounded-xl bg-white border text-[10px] font-bold text-slate-700">إشعار الدفع</a>}</div></div>)}</div><div className="p-4 border-t bg-slate-50"><button onClick={onOpenSupport} className="w-full py-2.5 px-4 rounded-xl bg-white border text-slate-700 font-bold text-xs flex items-center justify-center gap-2"><Phone className="w-4 h-4 text-purple-600"/>تواصل مع خدمة العملاء</button></div></div></div>;
};
